### ISSUE TITLE
Allow option to watch based on points instead of dollars?

### ISSUE THREAD

**Issue by jgoggan** [barrettc/swa-price-drop#4]
Thanks for this great script!  I normally book with points -- so it would be great if you could add a switch to do the same comparison, but using POINTS instead of DOLLARS for the "fareType"! I don't think it would be a difficult addition (and you could use the "outboundPrice" field in the configuration just as it is).

Thanks!

**Comment by barrettc** [comment]
Just pushed changes for this - give it a shot and let me know if it helps.

**Comment by jgoggan** [comment]
Awesome!  Works great -- thanks!

One minor thing for your next edit...  The Price Drop message that it generates still has the dollar sign ($).  So, even for points, it'll say something like:

**Price Drop: Outbound flight #1234 ABC->XYZ on 12/03/2017 is now $7777 (was $8888)**

Not a huge deal, but just mentioning it for you.  Thanks again -- this will be very useful!

**Comment by barrettc** [comment]
Oops - thanks, I'll tweak that

**Comment by barrettc** [comment]
@jgoggan Got around to tweaking that log message if you want to pull latest.
